#!/bin/bash
set -e

APP_NAME=$1

DIR_MAIN=$PWD

DIR_APP=$DIR_MAIN/$APP_NAME

echo '-------'
echo 'node -v'
node -v

echo '--------------'
echo 'yarn --version'
yarn --version

echo '-------------------'
echo 'cat /etc/os-release'
cat /etc/os-release

# Provide Git credentials
git config --global user.email 'rubyist@jasonhsu.com'
git config --global user.name 'Jason Hsu'

DATE_START=$(date +%s)

# Removing the old app (if necessary)
if [ -d "$DIR_APP" ]; then
  rm -rf $DIR_APP
fi

echo '--------------------------'
echo 'yarn global add gatsby-cli'
yarn global add gatsby-cli

echo '#############################################################################################'
echo "BEGIN: npx gatsby new $APP_NAME https://github.com/billyjacoby/gatsby-react-bootstrap-starter"
echo '#############################################################################################'
# Automatically selecting NPM instead of Yarn.
# Reason: Selecting NPM for Gatsby works for me.  Yarn doesn't.
echo -ne '\t\n' | npx gatsby new $APP_NAME https://github.com/billyjacoby/gatsby-react-bootstrap-starter
wait
echo '################################################################################################'
echo "FINISHED: npx gatsby new $APP_NAME https://github.com/billyjacoby/gatsby-react-bootstrap-starter"
echo '################################################################################################'

# WICHTIG/LEGACY/bash: Adding nukec.sh and nuke.sh
cp $DIR_MAIN/nukec.sh $DIR_APP
cp $DIR_MAIN/nuke.sh $DIR_APP

exit 0

# Add the mod directory and mod scripts to .gitignore
echo '' >> $DIR_APP/.gitignore
echo '# Files and directories from Docusaurus Neutrino' >> $DIR_APP/.gitignore
echo 'mod/*' >> $DIR_APP/.gitignore
echo 'mod-*' >> $DIR_APP/.gitignore
echo 'mod_app.sh' >> $DIR_APP/.gitignore

# Copy mod_app.sh to the new app's root directory
echo "cp $DIR_MAIN/mod_app.sh $DIR_APP"
cp $DIR_MAIN/mod_app.sh $DIR_APP

# Copy the mod directory to the new app's root directory
echo "cp -R $DIR_MAIN/mod $DIR_APP"
cp -R $DIR_MAIN/mod $DIR_APP

# Modify the new app
cd $DIR_APP && bash mod_app.sh '01'
cd $DIR_APP && bash mod_app.sh '02'
cd $DIR_APP && bash mod_app.sh '03'
cd $DIR_APP && bash mod_app.sh '04'

# Remove the mod* files from the new app
rm -rf $DIR_APP/mod
rm $DIR_APP/mod*

DATE_END=$(date +%s)

T_SEC=$((DATE_END-DATE_START))

echo '##########################################'
echo 'The new app has been created from scratch!'
echo 'It is in'
echo "$DIR_APP"
echo ''
echo "Time used:"
echo "$((T_SEC/60)) minutes and $((T_SEC%60)) seconds"
echo ''
