#!/bin/bash
set -e

echo '-------'
echo 'node -v'
docker-compose run --rm gatsby node -v

echo '-------------'
echo 'npm --version'
docker-compose run --rm gatsby npm --version

echo '--------------------'
echo 'npx gatsby --version'
docker-compose run --rm gatsby npx gatsby --version

echo '-------------------'
echo 'cat /etc/os-release'
docker-compose run --rm gatsby cat /etc/os-release

echo '---'
echo 'env'
docker-compose run --rm gatsby env
