#!/bin/bash
set -e

echo '-----------'
echo 'npm install'
docker-compose run --rm gatsby npm install

echo '--------------------'
echo 'npm run-script build'
docker-compose run --rm gatsby npm run-script build
